# Generated by Django 4.2.5 on 2023-10-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
