# Generated by Django 4.2.5 on 2023-10-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo'),
        ),
    ]
